### ISSUE TITLE
Error: GameJolt error: Incorrect trophy ID.

### ISSUE THREAD

**Issue by Raiper34** [luka712/gamejolt-ts-sdk#1]
Hi, 

I try to implement your game into your SDK, but it gives me `Error: GameJolt error: Incorrect trophy ID.` when I want to unlock the Trophy. What can be wrong? I have a proper Trophy ID from Gamejolt. Here is the implementation. It makes API call to 
```
https://api.gamejolt.com/api/game/v1_2/trophies/add_achieved/?game_id=779054&username=Raiper34&user_token=c0ada3&signature=3a847835ca4dbeecfc5ccb35db13e206
```
but do not see there my trophy id. Also, there is no trophy id in the request body.
```
game_id: 779054
username: Raiper34
user_token: c0ada3
signature: 3a847835ca4dbeecfc5ccb35db13e206
```
Do you hash it somehow?

**Comment by luka712** [comment]
@Raiper34 

Sorry for late reply,

Mistake on my part, parameter, should have been 
```
{ trophy_id: "some_id" }
```
instead of just passing string for trophy

However I have fixed that and now simply upgrading to newer version should work.

**Comment by Raiper34** [comment]
Works great! You can check it here https://gamejolt.com/games/build-a-snowman/779054
